import type { Metadata } from "next";
import "./globals.css";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`max-w-2xl mx-4 lg:mx-auto antialiased`}>
        <div className="my-20">{children}</div>
        <footer className="border-t py-5 flex justify-between items-center">
          <p className="text-xs">
            © {new Date().getFullYear()} Abyan Raditya, All right reserved.
          </p>
          <Link
            className="text-xs underline hover:no-underline"
            href="https://github.com/byanrkh/blog"
            target="_blank"
          >
            source code &#x2197;
          </Link>
        </footer>
      </body>
    </html>
  );
}
